"use client"

import { useState } from "react"
import Link from "next/link"
import {
  CalendarCheck,
  ChevronDown,
  ChevronUp,
  ShieldCheck,
  RotateCw,
  Scale,
} from "lucide-react"
import {
  DbMemberSubmission,
  dbMemberToTeamMember,
} from "@/lib/database.types"
import { getBurdenCounts, hasConsecutiveStretch } from "@/lib/rotation"
import type { RotationWeekData } from "@/lib/types"
import { formatHourLabel } from "@/lib/types"
import { MemberAvatar } from "@/components/ui/avatar"
import { PageBackLink } from "@/components/ui/page-back-link"
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip"
import {
  convertUtcToLocal,
  ensureDisplayTimezoneIana,
  getIanaShortLabel,
} from "@/lib/timezone"

type ExplainData = {
  shareablePlanExists?: boolean
  forcedSummary?: string
  forcedReason?: string
} | undefined

export function ScheduleAnalysisContent({
  scheduleId,
  scheduleName,
  teamName,
  weeksCount,
  modeLabel,
  explain,
  members,
  weeks,
  membersDisplay,
  scheduleBasePath,
  scheduleLinkParams,
  embedded,
  displayTimezone: displayTimezoneProp,
  modeUsed: modeUsedProp,
  useFixedBaseTime,
  relaxedWorkingHours,
  relaxedHardBoundaryMemberName,
}: {
  scheduleId: string
  scheduleName: string
  teamName: string
  weeksCount: number
  modeLabel: string
  explain: ExplainData
  members: DbMemberSubmission[]
  weeks: RotationWeekData[]
  membersDisplay: Map<string, { name: string; avatarUrl: string }>
  scheduleBasePath?: string
  scheduleLinkParams?: string
  embedded?: boolean
  displayTimezone?: string
  /** modeUsed from schedule.rotation_result — used for mode label detection. */
  modeUsed?: string
  /** When true (organizer toggled "Use a fixed base time"), always show FIXED TIME. */
  useFixedBaseTime?: boolean
  /** When true, preview was generated with relaxed working hours. */
  relaxedWorkingHours?: boolean
  /** When set, preview was generated by relaxing one hard boundary for this member. */
  relaxedHardBoundaryMemberName?: string | null
}) {
  const scheduleBasePathResolved = scheduleBasePath ?? "/schedule"
  const scheduleLinkSuffix = scheduleLinkParams ? `?${scheduleLinkParams}` : ""
  const displayTimezone = ensureDisplayTimezoneIana(
    displayTimezoneProp ?? "America/New_York"
  )

  const team = members.map((m) => {
    const base = dbMemberToTeamMember(m)
    const resolved = membersDisplay.get(m.id)
    return {
      ...base,
      name: resolved?.name ?? base.name,
      avatar_url: resolved?.avatarUrl ?? base.avatar_url,
    }
  })
  const burdenData = weeks.length ? getBurdenCounts(weeks, team) : []
  const maxMemberCount = burdenData.length
    ? Math.max(...burdenData.map((d) => d.count))
    : 0
  const minMemberCount = burdenData.length
    ? Math.min(...burdenData.map((d) => d.count))
    : 0
  const spread = maxMemberCount - minMemberCount
  const isEven = spread <= 1
  const consecutive = weeks.length ? hasConsecutiveStretch(weeks, team) : false
  const maxCount = burdenData.length
    ? Math.max(...burdenData.map((d) => d.count), 1)
    : 0

  const fairnessScore = Math.max(
    0,
    Math.min(100, 100 - spread * 8 - (consecutive ? 12 : 0))
  )

  const fairnessStatus =
    fairnessScore >= 90
      ? "Excellent balance"
      : fairnessScore >= 70
        ? "Good balance"
        : fairnessScore >= 50
          ? "Moderate imbalance"
          : "Poor balance"

  const fairnessBadgeStyle =
    fairnessScore >= 70
      ? "bg-emerald-500/15 text-emerald-700 dark:text-emerald-400"
      : fairnessScore >= 40
        ? "bg-amber-500/15 text-amber-700 dark:text-amber-400"
        : "bg-orange-500/15 text-orange-700 dark:text-orange-400"

  const rotationBarColor = (localHour: number) => {
    const h = ((localHour % 24) + 24) % 24
    if (h < 8) return "bg-blue-400/60"
    if (h >= 18) return "bg-orange-400/60"
    return "bg-muted-foreground/40"
  }

  const weekTimes = weeks.map((w) => {
    const dateIso = w.utcDateIso ?? "2025-03-05"
    const localHour = convertUtcToLocal(dateIso, w.utcHour, displayTimezone)
    return { week: w.week, localHour, label: formatHourLabel(localHour) }
  })

  const sacrificeTimeline = weeks.map((w) => {
    const dateIso = w.utcDateIso ?? "2025-03-05"
    const localHour = convertUtcToLocal(dateIso, w.utcHour, displayTimezone)
    const label = formatHourLabel(localHour)
    const inconveniencedMembers = w.memberTimes
      .filter((mt) => (mt.score ?? 0) > 0)
      .map((mt) => {
        const member = team.find((m) => m.id === mt.memberId)
        const display = membersDisplay.get(mt.memberId)
        const name = display?.name ?? member?.name ?? "—"
        const timezone = member?.timezone ?? "UTC"
        const city = getIanaShortLabel(timezone)
        return {
          memberId: mt.memberId,
          name,
          localTime: mt.localTime,
          city,
          timezone,
          localHour: mt.localHour,
        }
      })
    return {
      week: w.week,
      label,
      members: inconveniencedMembers,
    }
  })

  const timezoneRanges = (() => {
    const byTz = new Map<
      string,
      { min: number; max: number; city: string }
    >()
    for (const m of team) {
      const tz = m.timezone || "UTC"
      const city = getIanaShortLabel(tz)
      if (!byTz.has(tz)) {
        byTz.set(tz, { min: 24, max: 0, city })
      }
      const entry = byTz.get(tz)!
      for (const w of weeks) {
        const dateIso = w.utcDateIso ?? "2025-03-05"
        const localHour = convertUtcToLocal(dateIso, w.utcHour, tz)
        entry.min = Math.min(entry.min, localHour)
        entry.max = Math.max(entry.max, localHour)
      }
    }
    return Array.from(byTz.entries()).map(([tz, { min, max, city }]) => ({
      city,
      range: `${formatHourLabel(min)} – ${formatHourLabel(max)}`,
    }))
  })()

  const maxWidth = embedded ? "w-full max-w-none" : "max-w-6xl"
  const [timezoneExpanded, setTimezoneExpanded] = useState(false)

  const { modeDisplayLabel, modeDescription } = (() => {
    if (useFixedBaseTime === true) {
      return {
        modeDisplayLabel: "FIXED TIME",
        modeDescription: "Meeting time locked by organizer.",
      }
    }
    const mode = modeUsedProp?.toUpperCase()
    if (mode === "FALLBACK") {
      return {
        modeDisplayLabel: "BEST POSSIBLE",
        modeDescription: "Best available time within constraints.",
      }
    }
    return {
      modeDisplayLabel: "FAIR ROTATION",
      modeDescription: "Meeting time rotates across weeks.",
    }
  })()

  return (
    <main
      className={
        embedded
          ? `${maxWidth} px-4 py-6`
          : `mx-auto ${maxWidth} px-5 sm:px-8 pt-8 sm:pt-12 pb-8`
      }
    >
      {!embedded && (
        <PageBackLink
          href={`${scheduleBasePathResolved}/${scheduleId}${scheduleLinkSuffix}`}
          className="mb-4"
        >
          Back to schedule
        </PageBackLink>
      )}

      {!embedded && (
        <div className="mb-5">
          <p className="text-xs font-medium uppercase tracking-wider text-muted-foreground mb-1">
            Rotation Analysis
          </p>
          <h1 className="text-2xl sm:text-3xl font-semibold tracking-tight">
            {scheduleName}
          </h1>
        </div>
      )}

      {/* Schedule Overview — combined Fairness Score + Schedule Summary */}
      <section className="rounded-2xl border border-border/50 bg-card shadow-sm p-5 sm:p-6 mb-6">
        <h2 className="text-lg font-semibold tracking-tight mb-4">
          Schedule Overview
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 md:gap-8">
          {/* Left: Fairness Score */}
          <div>
            <h3 className="text-sm font-medium text-muted-foreground mb-1">
              Fairness Score
            </h3>
            <p className="text-4xl sm:text-5xl font-semibold tabular-nums">
              {fairnessScore}
              <span className="text-2xl sm:text-3xl font-normal text-muted-foreground ml-1">
                / 100
              </span>
            </p>
            <div className="mt-3 w-full max-w-xs">
              <div className="h-2 rounded-full bg-muted/60 overflow-hidden">
                <div
                  className="h-full rounded-full bg-primary/80 transition-all"
                  style={{ width: `${fairnessScore}%` }}
                />
              </div>
            </div>
            <span
              className={`inline-flex items-center rounded-md px-2.5 py-0.5 text-xs font-medium mt-2 ${fairnessBadgeStyle}`}
            >
              {fairnessStatus}
            </span>
            <p className="text-sm text-muted-foreground mt-3 max-w-sm">
              Measures how evenly meeting inconvenience is distributed.
            </p>
          </div>

          {/* Right: Schedule Summary metrics */}
          <div>
            <p className="text-base font-medium">{teamName}</p>
            <p className="text-sm text-muted-foreground mt-0.5">
              {weeksCount}-week rotation cycle
            </p>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 sm:gap-4 mt-4">
              <div>
                <p className="text-xl font-semibold tabular-nums text-primary">
                  {maxMemberCount}
                </p>
                <p className="text-[11px] text-muted-foreground">Max</p>
              </div>
              <div>
                <p className="text-xl font-semibold tabular-nums text-primary">
                  {isEven ? 0 : spread}
                </p>
                <p className="text-[11px] text-muted-foreground">Spread</p>
              </div>
              <div>
                <p className="text-xl font-semibold tabular-nums text-primary">
                  {burdenData.length}
                </p>
                <p className="text-[11px] text-muted-foreground">Members</p>
              </div>
              <div>
                <p className="text-xl font-semibold tabular-nums text-primary">
                  {weeksCount}
                </p>
                <p className="text-[11px] text-muted-foreground">Weeks</p>
              </div>
            </div>
            <div className="flex flex-col gap-1 mt-3">
              <span className="inline-flex w-fit items-center rounded-md bg-primary/15 text-primary px-2.5 py-0.5 text-xs font-medium">
                {modeDisplayLabel}
              </span>
              <p className="text-xs text-muted-foreground">
                {modeDescription}
              </p>
            </div>
            {explain?.shareablePlanExists === false && explain?.forcedSummary ? (
              <p className="text-xs text-muted-foreground mt-2">
                Schedule generated using fallback optimization mode.
              </p>
            ) : null}
          </div>
        </div>
        <p className="text-sm text-muted-foreground leading-relaxed mt-4 pt-4 border-t border-border/30">
          This schedule balances inconvenience across the team while respecting
          working hours and blocked time ranges.
        </p>
      </section>

      {/* Dashboard Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
        {/* Left column: Member Burden Distribution */}
        <div>
          <section className="rounded-2xl border border-border/50 bg-card shadow-sm p-5 sm:p-6">
            <h2 className="text-lg font-semibold tracking-tight">
              Member Burden Distribution
            </h2>
          <p className="text-xs text-muted-foreground mt-1 mb-4">
            Total inconvenience score across the {weeksCount}-week cycle.
          </p>
          {burdenData.length === 0 ? (
            <p className="text-sm text-muted-foreground">
              No burden data available for this schedule.
            </p>
          ) : (
            <div className="space-y-4">
              {burdenData.map((d) => {
                const isMax = d.count === maxMemberCount && maxMemberCount > 0
                return (
                  <div
                    key={d.memberId}
                    className={`flex items-center gap-3 rounded-lg px-2 py-1.5 -mx-2 -my-0.5 transition-colors ${
                      isMax ? "bg-muted/40" : ""
                    }`}
                  >
                    <MemberAvatar
                      avatarUrl={membersDisplay.get(d.memberId)?.avatarUrl}
                      name={d.name}
                      size="sm"
                      className="shrink-0"
                    />
                    <span className="text-sm font-medium w-24 sm:w-28 truncate">
                      {d.name}
                    </span>
                    <div className="flex-1 h-2.5 rounded-full bg-muted/60 overflow-hidden min-w-0">
                      <div
                        className="h-full rounded-full bg-stretch/80 transition-all duration-500 relative overflow-hidden"
                        style={{
                          width: `${maxCount > 0 ? (d.count / maxCount) * 100 : 0}%`,
                        }}
                      >
                        {d.sacrificeCount > 0 && d.count > 0 && (
                          <div
                            className="absolute right-0 top-0 bottom-0 bg-stretch-foreground/20 rounded-r-full"
                            style={{
                              width: `${Math.min(100, ((d.sacrificePoints ?? d.sacrificeCount) / d.count) * 100)}%`,
                            }}
                          />
                        )}
                      </div>
                    </div>
                    <span
                      className={`text-sm tabular-nums w-8 text-right shrink-0 ${
                        isMax ? "font-bold text-foreground" : "font-medium"
                      }`}
                    >
                      {d.count}
                    </span>
                  </div>
                )
              })}
            </div>
          )}
          <p className="text-xs text-muted-foreground/80 mt-4 leading-relaxed">
            Burden scores represent early or late meetings outside ideal working
            hours. Lower scores indicate more comfortable schedules.
          </p>
        </section>
        </div>

        {/* Right column: Meeting Time Rotation */}
        <div>
          <section className="rounded-2xl border border-border/50 bg-card shadow-sm p-5 sm:p-6">
            <h2 className="text-lg font-semibold tracking-tight">
              Meeting Time Rotation
            </h2>
            <p className="text-xs text-muted-foreground mt-1 mb-4">
              How meeting time shifts across weeks.
            </p>
            {weekTimes.length === 0 ? (
              <p className="text-sm text-muted-foreground">
                No week data available.
              </p>
            ) : (
              <div className="space-y-2">
                {weekTimes.map(({ week, label, localHour }) => {
                  const h = ((localHour % 24) + 24) % 24
                  const dayPct = (h / 24) * 100
                  return (
                    <div
                      key={week}
                      className="flex items-center gap-3"
                    >
                      <span className="text-xs font-medium text-muted-foreground w-14 shrink-0">
                        Week {week}
                      </span>
                      <span className="text-sm tabular-nums w-20 shrink-0">
                        {label}
                      </span>
                      <div className="flex-1 h-1.5 rounded-full bg-muted/60 overflow-hidden min-w-0">
                        <div
                          className={`h-full rounded-full transition-all ${rotationBarColor(localHour)}`}
                          style={{ width: `${dayPct}%` }}
                        />
                      </div>
                    </div>
                  )
                })}
              </div>
            )}
          </section>
        </div>
      </div>

      {/* Sacrifice Timeline — horizontal, 2 rows of 6, compact */}
      <section className="rounded-2xl border border-border/50 bg-card shadow-sm p-4 sm:p-5 mb-6">
        <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between sm:gap-4 mb-3">
          <div>
            <h2 className="text-lg font-semibold tracking-tight">
              Sacrifice Timeline
            </h2>
            <p className="text-xs text-muted-foreground mt-0.5">
              How meeting inconvenience is distributed each week. Each dot = one
              member outside preferred hours.
            </p>
          </div>
          <div className="flex flex-wrap gap-x-4 gap-y-1 mt-2 sm:mt-1 text-[11px] text-muted-foreground">
            <span className="flex items-center gap-1.5">
              <span className="size-2 rounded-full bg-blue-400/60 shrink-0" />
              Early meeting
            </span>
            <span className="flex items-center gap-1.5">
              <span className="size-2 rounded-full bg-orange-400/60 shrink-0" />
              Late meeting
            </span>
            <span className="flex items-center gap-1.5">
              <span className="size-2 rounded-full bg-muted-foreground/50 shrink-0" />
              Mild inconvenience
            </span>
          </div>
        </div>
        {sacrificeTimeline.length === 0 ? (
          <p className="text-sm text-muted-foreground">
            No week data available.
          </p>
        ) : (
          <TooltipProvider delayDuration={100}>
            <div className="grid grid-cols-3 sm:grid-cols-6 gap-x-4 gap-y-4">
              {sacrificeTimeline.map(({ week, label, members }) => {
                const dotColor = (h: number) => {
                  const nh = ((h % 24) + 24) % 24
                  if (nh < 8) return "bg-blue-400/60"
                  if (nh >= 18) return "bg-orange-400/60"
                  return "bg-muted-foreground/50"
                }
                return (
                  <div
                    key={week}
                    className="flex flex-col gap-1 min-w-0"
                  >
                    <div className="flex items-baseline gap-1.5">
                      <span className="text-xs font-medium text-muted-foreground shrink-0">
                        Week {week}
                      </span>
                      <span className="text-[11px] tabular-nums text-muted-foreground truncate">
                        {label}
                      </span>
                    </div>
                    <div className="flex items-center gap-0.5 flex-wrap min-h-[20px]">
                      {members.length === 0 ? (
                        <span className="text-[10px] text-muted-foreground/60">
                          —
                        </span>
                      ) : (
                        members.map((m) => (
                          <Tooltip key={m.memberId}>
                            <TooltipTrigger asChild>
                              <span
                                className={`size-2 rounded-full shrink-0 cursor-default ${dotColor(m.localHour)}`}
                              />
                            </TooltipTrigger>
                            <TooltipContent side="top" className="max-w-[220px]">
                              <p className="font-medium">{m.name}</p>
                              <p className="opacity-90 mt-0.5">
                                Timezone: {m.timezone}
                              </p>
                              <p className="opacity-90">
                                Meeting time: {m.localTime}
                              </p>
                            </TooltipContent>
                          </Tooltip>
                        ))
                      )}
                    </div>
                  </div>
                )
              })}
            </div>
          </TooltipProvider>
        )}
      </section>

      {/* Timezone Impact — collapsible, full width */}
      <section className="rounded-2xl border border-border/50 bg-card shadow-sm overflow-hidden mb-6">
        <button
          type="button"
          onClick={() => setTimezoneExpanded((v) => !v)}
          className="flex w-full items-center justify-between gap-4 p-5 sm:p-6 text-left hover:bg-muted/30 transition-colors"
        >
          <div>
            <h2 className="text-lg font-semibold tracking-tight">
              Timezone Impact
            </h2>
            <p className="text-xs text-muted-foreground mt-0.5">
              Relative meeting time range per timezone.
            </p>
          </div>
          <span className="shrink-0 text-muted-foreground">
            {timezoneExpanded ? (
              <ChevronUp className="size-5" />
            ) : (
              <ChevronDown className="size-5" />
            )}
          </span>
        </button>
        <div
          className="overflow-hidden transition-[max-height] duration-200 ease-in-out"
          style={{
            maxHeight: timezoneExpanded ? "400px" : "0",
          }}
        >
          <div className="px-5 sm:px-6 pb-5 sm:pb-6 pt-0">
              {timezoneRanges.length === 0 ? (
                <p className="text-sm text-muted-foreground">
                  No timezone data available.
                </p>
              ) : (
                <div className="space-y-2">
                  {timezoneRanges.map(({ city, range }) => (
                    <div
                      key={city}
                      className="flex items-center justify-between gap-4 py-1.5"
                    >
                      <span className="text-sm font-medium shrink-0">
                        {city}
                      </span>
                      <span className="text-xs text-muted-foreground tabular-nums text-right min-w-[140px]">
                        {range}
                      </span>
                    </div>
                  ))}
                </div>
              )}
            </div>
        </div>
      </section>

      {/* Explanation Section — Bottom */}
      <section className="rounded-2xl border border-border/50 bg-card shadow-sm p-5 sm:p-6">
        <h2 className="text-lg font-semibold tracking-tight mb-4">
          Why this schedule was selected
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {relaxedWorkingHours ? (
            <div className="rounded-xl border border-border/40 bg-muted/20 p-4 space-y-2 transition-all duration-200 hover:border-primary/20 hover:shadow-sm">
              <div className="flex size-9 items-center justify-center rounded-full bg-primary/10 text-primary">
                <CalendarCheck className="size-5" />
              </div>
              <h3 className="text-sm font-semibold">Working hours relaxed</h3>
              <p className="text-xs text-muted-foreground leading-relaxed">
                This preview allows meeting times slightly outside normal working hours.
              </p>
            </div>
          ) : (
            <div className="rounded-xl border border-border/40 bg-muted/20 p-4 space-y-2 transition-all duration-200 hover:border-primary/20 hover:shadow-sm">
              <div className="flex size-9 items-center justify-center rounded-full bg-primary/10 text-primary">
                <CalendarCheck className="size-5" />
              </div>
              <h3 className="text-sm font-semibold">Availability checked</h3>
              <p className="text-xs text-muted-foreground leading-relaxed">
                All members&apos; working hours were evaluated.
              </p>
            </div>
          )}
          {relaxedHardBoundaryMemberName ? (
            <div className="rounded-xl border border-border/40 bg-muted/20 p-4 space-y-2 transition-all duration-200 hover:border-primary/20 hover:shadow-sm">
              <div className="flex size-9 items-center justify-center rounded-full bg-primary/10 text-primary">
                <ShieldCheck className="size-5" />
              </div>
              <h3 className="text-sm font-semibold">Hard boundary temporarily relaxed</h3>
              <p className="text-xs text-muted-foreground leading-relaxed">
                {relaxedHardBoundaryMemberName
                  ? `One blocked time range was relaxed for ${relaxedHardBoundaryMemberName} in this preview.`
                  : "One blocked time range was temporarily relaxed in this preview."}
              </p>
            </div>
          ) : (
            <div className="rounded-xl border border-border/40 bg-muted/20 p-4 space-y-2 transition-all duration-200 hover:border-primary/20 hover:shadow-sm">
              <div className="flex size-9 items-center justify-center rounded-full bg-primary/10 text-primary">
                <ShieldCheck className="size-5" />
              </div>
              <h3 className="text-sm font-semibold">Hard boundaries respected</h3>
              <p className="text-xs text-muted-foreground leading-relaxed">
                No meetings were scheduled during blocked time ranges.
              </p>
            </div>
          )}
          <div className="rounded-xl border border-border/40 bg-muted/20 p-4 space-y-2 transition-all duration-200 hover:border-primary/20 hover:shadow-sm">
            <div className="flex size-9 items-center justify-center rounded-full bg-primary/10 text-primary">
              <RotateCw className="size-5" />
            </div>
            <h3 className="text-sm font-semibold">Fairness rotation</h3>
            <p className="text-xs text-muted-foreground leading-relaxed">
              Meeting inconvenience rotates across the team.
            </p>
          </div>
          <div className="rounded-xl border border-border/40 bg-muted/20 p-4 space-y-2 transition-all duration-200 hover:border-primary/20 hover:shadow-sm">
            <div className="flex size-9 items-center justify-center rounded-full bg-primary/10 text-primary">
              <Scale className="size-5" />
            </div>
            <h3 className="text-sm font-semibold">Balanced burden</h3>
            <p className="text-xs text-muted-foreground leading-relaxed">
              No single member carries the majority of early/late meetings.
            </p>
          </div>
        </div>
      </section>

      {!embedded && (
        <div className="pt-6">
          <PageBackLink
            href={`${scheduleBasePathResolved}/${scheduleId}${scheduleLinkSuffix}`}
            className="mb-0"
          >
            Back to schedule
          </PageBackLink>
        </div>
      )}
    </main>
  )
}
