"use client"

import { useState } from "react"
import Link from "next/link"
import {
  CalendarCheck,
  ChevronDown,
  ChevronUp,
  ShieldCheck,
  RotateCw,
  Users,
  BarChart3,
  Zap,
} from "lucide-react"
import {
  DbMemberSubmission,
  dbMemberToTeamMember,
} from "@/lib/database.types"
import { getBurdenCounts, hasConsecutiveStretch } from "@/lib/rotation"
import type { RotationWeekData } from "@/lib/types"
import { formatHourLabel } from "@/lib/types"
import { MemberAvatar } from "@/components/ui/avatar"
import { PageBackLink } from "@/components/ui/page-back-link"
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip"
import {
  convertUtcToLocal,
  ensureDisplayTimezoneIana,
  getIanaShortLabel,
} from "@/lib/timezone"

type ExplainData = {
  shareablePlanExists?: boolean
  forcedSummary?: string
  forcedReason?: string
} | undefined

export function ScheduleAnalysisContent({
  scheduleId,
  scheduleName,
  teamName,
  weeksCount,
  modeLabel,
  explain,
  members,
  weeks,
  membersDisplay,
  scheduleBasePath,
  scheduleLinkParams,
  embedded,
  displayTimezone: displayTimezoneProp,
  modeUsed: modeUsedProp,
  useFixedBaseTime,
  relaxedWorkingHours,
  relaxedHardBoundaryMemberName,
  demoMode,
  onBackToSchedule,
}: {
  scheduleId: string
  scheduleName: string
  teamName: string
  weeksCount: number
  modeLabel: string
  explain: ExplainData
  members: DbMemberSubmission[]
  weeks: RotationWeekData[]
  membersDisplay: Map<string, { name: string; avatarUrl: string }>
  scheduleBasePath?: string
  scheduleLinkParams?: string
  embedded?: boolean
  displayTimezone?: string
  /** modeUsed from schedule.rotation_result — used for mode label detection. */
  modeUsed?: string
  /** When true (organizer toggled "Use a fixed base time"), always show FIXED TIME. */
  useFixedBaseTime?: boolean
  /** When true, preview was generated with relaxed working hours. */
  relaxedWorkingHours?: boolean
  /** When set, preview was generated by relaxing one hard boundary for this member. */
  relaxedHardBoundaryMemberName?: string | null
  /** When true, use demo handlers for navigation. */
  demoMode?: boolean
  onBackToSchedule?: () => void
}) {
  const scheduleBasePathResolved = scheduleBasePath ?? "/schedule"
  const scheduleLinkSuffix = scheduleLinkParams ? `?${scheduleLinkParams}` : ""
  const displayTimezone = ensureDisplayTimezoneIana(
    displayTimezoneProp ?? "America/New_York"
  )

  const team = members.map((m) => {
    const base = dbMemberToTeamMember(m)
    const resolved = membersDisplay.get(m.id)
    return {
      ...base,
      name: resolved?.name ?? base.name,
      avatar_url: resolved?.avatarUrl ?? base.avatar_url,
    }
  })
  const burdenData = weeks.length ? getBurdenCounts(weeks, team) : []
  const maxMemberCount = burdenData.length
    ? Math.max(...burdenData.map((d) => d.count))
    : 0
  const minMemberCount = burdenData.length
    ? Math.min(...burdenData.map((d) => d.count))
    : 0
  const spread = maxMemberCount - minMemberCount
  const isEven = spread <= 1
  const consecutive = weeks.length ? hasConsecutiveStretch(weeks, team) : false
  const maxCount = burdenData.length
    ? Math.max(...burdenData.map((d) => d.count), 1)
    : 0

  const fairnessScore = Math.max(
    0,
    Math.min(100, 100 - spread * 8 - (consecutive ? 12 : 0))
  )

  const fairnessStatus =
    fairnessScore >= 90
      ? "Excellent balance"
      : fairnessScore >= 70
        ? "Good balance"
        : fairnessScore >= 50
          ? "Moderate imbalance"
          : "Poor balance"

  const weekTimes = weeks.map((w) => {
    const dateIso = w.utcDateIso ?? "2025-03-05"
    const localHour = convertUtcToLocal(dateIso, w.utcHour, displayTimezone)
    return { week: w.week, localHour, label: formatHourLabel(localHour) }
  })

  const sacrificeTimeline = weeks.map((w) => {
    const dateIso = w.utcDateIso ?? "2025-03-05"
    const localHour = convertUtcToLocal(dateIso, w.utcHour, displayTimezone)
    const label = formatHourLabel(localHour)
    const inconveniencedMembers = w.memberTimes
      .filter((mt) => (mt.score ?? 0) > 0)
      .map((mt) => {
        const member = team.find((m) => m.id === mt.memberId)
        const display = membersDisplay.get(mt.memberId)
        const name = display?.name ?? member?.name ?? "—"
        const timezone = member?.timezone ?? "UTC"
        const city = getIanaShortLabel(timezone)
        return {
          memberId: mt.memberId,
          name,
          localTime: mt.localTime,
          city,
          timezone,
          localHour: mt.localHour,
        }
      })
    return {
      week: w.week,
      label,
      members: inconveniencedMembers,
    }
  })

  const timezoneRanges = (() => {
    const byTz = new Map<
      string,
      { min: number; max: number; city: string }
    >()
    for (const m of team) {
      const tz = m.timezone || "UTC"
      const city = getIanaShortLabel(tz)
      if (!byTz.has(tz)) {
        byTz.set(tz, { min: 24, max: 0, city })
      }
      const entry = byTz.get(tz)!
      for (const w of weeks) {
        const dateIso = w.utcDateIso ?? "2025-03-05"
        const localHour = convertUtcToLocal(dateIso, w.utcHour, tz)
        entry.min = Math.min(entry.min, localHour)
        entry.max = Math.max(entry.max, localHour)
      }
    }
    return Array.from(byTz.entries()).map(([tz, { min, max, city }]) => ({
      city,
      range: `${formatHourLabel(min)} – ${formatHourLabel(max)}`,
    }))
  })()

  const maxWidth = embedded ? "w-full max-w-none" : "max-w-6xl"
  const [timezoneExpanded, setTimezoneExpanded] = useState(false)

  const { modeDisplayLabel, modeDescription } = (() => {
    if (useFixedBaseTime === true) {
      return {
        modeDisplayLabel: "FIXED TIME",
        modeDescription: "Meeting time locked by organizer.",
      }
    }
    const mode = modeUsedProp?.toUpperCase()
    if (mode === "FALLBACK") {
      return {
        modeDisplayLabel: "BEST POSSIBLE",
        modeDescription: "Best available time within constraints.",
      }
    }
    return {
      modeDisplayLabel: "FAIR ROTATION",
      modeDescription: "Meeting time rotates across weeks.",
    }
  })()

  return (
    <main
      className={
        embedded
          ? `${maxWidth} px-4 py-6`
          : `max-w-5xl mx-auto px-6 py-8`
      }
    >
      {!embedded && (
        <PageBackLink
          href={demoMode ? undefined : `${scheduleBasePathResolved}/${scheduleId}${scheduleLinkSuffix}`}
          onClick={demoMode ? onBackToSchedule : undefined}
          className="mb-6"
        >
          Back to schedule
        </PageBackLink>
      )}

      {!embedded && (
        <div className="mb-8">
          <span className="text-[#0d9488] text-[0.75rem] tracking-widest uppercase block mb-1 font-semibold">
            Rotation Analysis
          </span>
          <h1 className="text-[1.6rem] text-[#1a1a2e] tracking-[-0.03em] font-semibold">
            {scheduleName}
          </h1>
        </div>
      )}

      {/* Schedule Overview — combined Fairness Score + Schedule Summary */}
      <section className="rounded-2xl border border-[#edeef0] bg-white shadow-[0_1px_4px_rgba(0,0,0,0.03)] p-5 sm:p-6 mb-6 hover:shadow-[0_2px_8px_rgba(0,0,0,0.04)] transition-shadow">
        <h2 className="text-[#1a1a2e] text-[0.95rem] font-semibold mb-5">
          Schedule Overview
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 md:gap-8">
          {/* Left: Fairness Score */}
          <div>
            <p className="text-[#9ca3af] text-[0.82rem] mb-2">Fairness Score</p>
            <div className="flex items-baseline gap-1 mb-3">
              <span className="text-[2.6rem] text-[#1a1a2e] tracking-[-0.04em] leading-none font-bold tabular-nums">
                {fairnessScore}
              </span>
              <span className="text-[1.1rem] text-[#c4c7cc] font-normal">/ 100</span>
            </div>
            <div className="w-full h-2 bg-[#f0f0f2] rounded-full overflow-hidden mb-3">
              <div
                className="h-full rounded-full bg-gradient-to-r from-[#0d9488] to-[#14b8a6] transition-all duration-500"
                style={{ width: `${fairnessScore}%` }}
              />
            </div>
            <span
              className={`inline-flex rounded-md px-2.5 py-1 text-[0.72rem] font-medium ${
                fairnessScore >= 70
                  ? "text-[#0d9488] bg-[#f0fdfa] border border-[#0d9488]/15"
                  : fairnessScore >= 40
                    ? "text-[#d97706] bg-[#fffbeb] border border-[#f59e0b]/20"
                    : "text-[#d97706] bg-[#fffbeb] border border-[#f59e0b]/20"
              }`}
            >
              {fairnessStatus}
            </span>
            <p className="text-[#9ca3af] text-[0.78rem] mt-2 leading-relaxed">
              Measures how evenly meeting inconvenience is distributed.
            </p>
          </div>

          {/* Right: Schedule Summary metrics */}
          <div>
            <p className="text-[#1a1a2e] text-[0.88rem] font-medium mb-0.5">
              {teamName}
            </p>
            <p className="text-[#9ca3af] text-[0.78rem] mb-4">
              {weeksCount}-week rotation cycle
            </p>
            <div className="grid grid-cols-4 gap-3 mb-4">
              <div className="text-center">
                <div className="text-[1.2rem] text-[#0d9488] font-bold tabular-nums">
                  {maxMemberCount}
                </div>
                <div className="text-[0.7rem] text-[#9ca3af] mt-0.5">Max</div>
              </div>
              <div className="text-center">
                <div className="text-[1.2rem] text-[#0d9488] font-bold tabular-nums">
                  {isEven ? 0 : spread}
                </div>
                <div className="text-[0.7rem] text-[#9ca3af] mt-0.5">Spread</div>
              </div>
              <div className="text-center">
                <div className="text-[1.2rem] text-[#0d9488] font-bold tabular-nums">
                  {burdenData.length}
                </div>
                <div className="text-[0.7rem] text-[#9ca3af] mt-0.5">Members</div>
              </div>
              <div className="text-center">
                <div className="text-[1.2rem] text-[#0d9488] font-bold tabular-nums">
                  {weeksCount}
                </div>
                <div className="text-[0.7rem] text-[#9ca3af] mt-0.5">Weeks</div>
              </div>
            </div>
            <span className="inline-flex text-[0.68rem] font-semibold text-white bg-[#0d9488] px-2.5 py-1 rounded-md">
              {modeDisplayLabel}
            </span>
            <div className="mt-2 space-y-0.5">
              <p className="text-[#6b7280] text-[0.78rem]">{modeDescription}</p>
              {explain?.shareablePlanExists === false && explain?.forcedSummary ? (
                <p className="text-[#9ca3af] text-[0.75rem]">
                  Schedule generated using fallback optimization mode.
                </p>
              ) : null}
            </div>
          </div>
        </div>
        <div className="mt-5 pt-4 border-t border-[#f0f0f2]">
          <p className="text-[#6b7280] text-[0.82rem] leading-relaxed">
            This schedule balances inconvenience across the team while respecting
            working hours and blocked time ranges.
          </p>
        </div>
      </section>

      {/* Dashboard Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
        {/* Left column: Member Burden Distribution */}
        <div>
          <section className="rounded-2xl border border-[#edeef0] bg-white shadow-[0_1px_4px_rgba(0,0,0,0.03)] p-5 sm:p-6 hover:shadow-[0_2px_8px_rgba(0,0,0,0.04)] transition-shadow">
            <div className="flex items-center gap-2 mb-1">
              <Users size={15} className="text-[#0d9488] shrink-0" />
              <h2 className="text-[#1a1a2e] text-[0.9rem] font-semibold">
                Member Burden Distribution
              </h2>
            </div>
            <p className="text-[#9ca3af] text-[0.78rem] mb-5">
              Total inconvenience score across the {weeksCount}-week cycle.
            </p>
            {burdenData.length === 0 ? (
              <p className="text-[#9ca3af] text-[0.82rem]">
                No burden data available for this schedule.
              </p>
            ) : (
              <div className="space-y-3">
                {burdenData.map((d) => {
                  const isMax = d.count === maxMemberCount && maxMemberCount > 0
                  return (
                    <div
                      key={d.memberId}
                      className={`flex items-center gap-2.5 ${
                        isMax ? "rounded-lg bg-[#fef8f0]/50 px-2 py-1 -mx-2" : ""
                      }`}
                    >
                      <MemberAvatar
                        avatarUrl={membersDisplay.get(d.memberId)?.avatarUrl}
                        name={d.name}
                        size="sm"
                        className="shrink-0 size-7"
                      />
                      <span className="text-[0.82rem] text-[#1a1a2e] font-medium w-24 sm:w-28 truncate shrink-0">
                        {d.name}
                      </span>
                      <div className="flex-1 h-2 bg-[#f0f0f2] rounded-full overflow-hidden min-w-0">
                        <div
                          className="h-full rounded-full transition-all duration-500 relative overflow-hidden"
                          style={{
                            width: `${maxCount > 0 ? (d.count / maxCount) * 100 : 4}%`,
                            backgroundColor: d.count > 0 ? "#f5c882" : "#e5e7eb",
                          }}
                        >
                          {d.sacrificeCount > 0 && d.count > 0 && (
                            <div
                              className="absolute right-0 top-0 bottom-0 bg-[#d97706]/20 rounded-r-full"
                              style={{
                                width: `${Math.min(100, ((d.sacrificePoints ?? d.sacrificeCount) / d.count) * 100)}%`,
                              }}
                            />
                          )}
                        </div>
                      </div>
                      <span
                        className={`text-[0.84rem] tabular-nums w-5 text-right shrink-0 ${
                          d.count > 0 ? "text-[#d97706] font-semibold" : "text-[#c4c7cc] font-normal"
                        }`}
                      >
                        {d.count}
                      </span>
                    </div>
                  )
                })}
              </div>
            )}
            <p className="text-[#b0b4bc] text-[0.75rem] mt-5 leading-relaxed">
              Burden scores represent early or late meetings outside ideal working
              hours. Lower scores indicate more comfortable schedules.
            </p>
          </section>
        </div>

        {/* Right column: Meeting Time Rotation */}
        <div>
          <section className="rounded-2xl border border-[#edeef0] bg-white shadow-[0_1px_4px_rgba(0,0,0,0.03)] p-5 sm:p-6 hover:shadow-[0_2px_8px_rgba(0,0,0,0.04)] transition-shadow">
            <div className="flex items-center gap-2 mb-1">
              <BarChart3 size={15} className="text-[#0d9488] shrink-0" />
              <h2 className="text-[#1a1a2e] text-[0.9rem] font-semibold">
                Meeting Time Rotation
              </h2>
            </div>
            <p className="text-[#9ca3af] text-[0.78rem] mb-5">
              How meeting time shifts across weeks.
            </p>
            {weekTimes.length === 0 ? (
              <p className="text-[#9ca3af] text-[0.82rem]">
                No week data available.
              </p>
            ) : (
              <div className="space-y-3">
                {weekTimes.map(({ week, label, localHour }) => {
                  const h = ((localHour % 24) + 24) % 24
                  const dayPct = (h / 24) * 100
                  const isHeaviest = h < 8 || h >= 18
                  return (
                    <div key={week} className="flex items-center gap-3">
                      <span className="text-[0.78rem] text-[#9ca3af] w-12 shrink-0">
                        Week {week}
                      </span>
                      <span className="text-[0.84rem] text-[#1a1a2e] font-medium w-20 shrink-0 tabular-nums">
                        {label}
                      </span>
                      <div className="flex-1 h-3 bg-[#f0f0f2] rounded-full overflow-hidden min-w-0">
                        <div
                          className="h-full rounded-full transition-all duration-500"
                          style={{
                            width: `${dayPct}%`,
                            backgroundColor: isHeaviest ? "#374151" : "#a7e8de",
                          }}
                        />
                      </div>
                    </div>
                  )
                })}
              </div>
            )}
          </section>
        </div>
      </div>

      {/* Sacrifice Timeline — horizontal, 2 rows of 6, compact */}
      <section className="rounded-2xl border border-[#edeef0] bg-white shadow-[0_1px_4px_rgba(0,0,0,0.03)] p-5 sm:p-6 mb-6 hover:shadow-[0_2px_8px_rgba(0,0,0,0.04)] transition-shadow">
        <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between sm:gap-4 mb-4">
          <div className="flex items-center gap-2">
            <Zap size={15} className="text-[#0d9488] shrink-0" />
            <h2 className="text-[#1a1a2e] text-[0.9rem] font-semibold">
              Sacrifice Timeline
            </h2>
          </div>
          <div className="flex flex-wrap items-center gap-4 text-[0.72rem] text-[#9ca3af]">
            <span className="flex items-center gap-1.5">
              <span className="size-2 rounded-full bg-comfortable/70 shrink-0" />
              Early meeting
            </span>
            <span className="flex items-center gap-1.5">
              <span className="size-2 rounded-full bg-stretch/70 shrink-0" />
              Late meeting
            </span>
            <span className="flex items-center gap-1.5">
              <span className="size-2 rounded-full bg-muted-foreground/50 shrink-0" />
              Mild inconvenience
            </span>
          </div>
        </div>
        <p className="text-[#9ca3af] text-[0.78rem] mb-5">
          How meeting inconvenience is distributed each week. Each dot = one
          member outside preferred hours.
        </p>
        {sacrificeTimeline.length === 0 ? (
          <p className="text-[#9ca3af] text-[0.82rem]">
            No week data available.
          </p>
        ) : (
          <TooltipProvider delayDuration={100}>
            <div className="grid grid-cols-3 sm:grid-cols-6 gap-x-6 gap-y-4">
              {sacrificeTimeline.map(({ week, label, members }) => {
                const dotColor = (h: number) => {
                  const nh = ((h % 24) + 24) % 24
                  if (nh < 8) return "bg-comfortable/70"
                  if (nh >= 18) return "bg-stretch/70"
                  return "bg-muted-foreground/50"
                }
                return (
                  <div
                    key={week}
                    className="flex flex-col gap-1 min-w-0"
                  >
                    <div className="flex items-baseline gap-1.5">
                      <span className="text-[0.75rem] font-medium text-[#9ca3af] shrink-0">
                        Week {week}
                      </span>
                      <span className="text-[0.78rem] tabular-nums text-[#6b7280] truncate font-medium">
                        {label}
                      </span>
                    </div>
                    <div className="flex items-center gap-0.5 flex-wrap min-h-[20px]">
                      {members.length === 0 ? (
                        <span className="text-[10px] text-muted-foreground/60">
                          —
                        </span>
                      ) : (
                        members.map((m) => (
                          <Tooltip key={m.memberId}>
                            <TooltipTrigger asChild>
                              <span
                                className={`size-2 rounded-full shrink-0 cursor-default ${dotColor(m.localHour)}`}
                              />
                            </TooltipTrigger>
                            <TooltipContent side="top" className="max-w-[220px]">
                              <p className="font-medium">{m.name}</p>
                              <p className="opacity-90 mt-0.5">
                                Timezone: {m.timezone}
                              </p>
                              <p className="opacity-90">
                                Meeting time: {m.localTime}
                              </p>
                            </TooltipContent>
                          </Tooltip>
                        ))
                      )}
                    </div>
                  </div>
                )
              })}
            </div>
          </TooltipProvider>
        )}
      </section>

      {/* Timezone Impact — collapsible, full width */}
      <section className="rounded-2xl border border-[#edeef0] bg-white shadow-[0_1px_4px_rgba(0,0,0,0.03)] overflow-hidden mb-6 hover:shadow-[0_2px_8px_rgba(0,0,0,0.04)] transition-shadow">
        <button
          type="button"
          onClick={() => setTimezoneExpanded((v) => !v)}
          className="flex w-full items-center justify-between gap-4 px-5 py-5 text-left hover:bg-[#f9fafb]/50 transition-colors cursor-pointer"
        >
          <div>
            <h2 className="text-[#1a1a2e] text-[0.9rem] font-semibold">
              Timezone Impact
            </h2>
            <p className="text-[#9ca3af] text-[0.78rem] mt-0.5">
              Relative meeting time range per timezone.
            </p>
          </div>
          <span className="shrink-0 text-[#9ca3af]">
            {timezoneExpanded ? (
              <ChevronUp size={18} />
            ) : (
              <ChevronDown size={18} />
            )}
          </span>
        </button>
        <div
          className="overflow-hidden transition-[max-height] duration-200 ease-in-out"
          style={{
            maxHeight: timezoneExpanded ? "400px" : "0",
          }}
        >
          <div className="px-5 pb-5 pt-0">
              {timezoneRanges.length === 0 ? (
                <p className="text-[#9ca3af] text-[0.82rem]">
                  No timezone data available.
                </p>
              ) : (
                <div className="space-y-0">
                  {timezoneRanges.map(({ city, range }) => (
                    <div
                      key={city}
                      className="flex items-center justify-between py-3 border-b border-[#f5f5f7] last:border-b-0"
                    >
                      <span className="text-[0.86rem] text-[#1a1a2e] font-medium shrink-0">
                        {city}
                      </span>
                      <span className="text-[0.84rem] text-[#6b7280] tabular-nums text-right">
                        {range}
                      </span>
                    </div>
                  ))}
                </div>
              )}
            </div>
        </div>
      </section>

      {/* Explanation Section — Bottom */}
      <section className="rounded-2xl border border-[#edeef0] bg-white shadow-[0_1px_4px_rgba(0,0,0,0.03)] p-5 sm:p-6 hover:shadow-[0_2px_8px_rgba(0,0,0,0.04)] transition-shadow">
        <h2 className="text-[#1a1a2e] text-[0.95rem] font-semibold mb-5">
          Why this schedule was selected
        </h2>
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
          {relaxedWorkingHours ? (
            <div className="bg-[#f9fafb] rounded-xl p-4 hover:bg-[#f0fdfa] transition-colors duration-200">
              <div className="w-9 h-9 rounded-xl bg-[#f0fdfa] border border-[#0d9488]/10 flex items-center justify-center mb-3">
                <CalendarCheck size={17} className="text-[#0d9488]" />
              </div>
              <h3 className="text-[#1a1a2e] text-[0.84rem] font-semibold mb-1">Working hours relaxed</h3>
              <p className="text-[#9ca3af] text-[0.78rem] leading-relaxed">
                This preview allows meeting times slightly outside normal working hours.
              </p>
            </div>
          ) : (
            <div className="bg-[#f9fafb] rounded-xl p-4 hover:bg-[#f0fdfa] transition-colors duration-200">
              <div className="w-9 h-9 rounded-xl bg-[#f0fdfa] border border-[#0d9488]/10 flex items-center justify-center mb-3">
                <CalendarCheck size={17} className="text-[#0d9488]" />
              </div>
              <h3 className="text-[#1a1a2e] text-[0.84rem] font-semibold mb-1">Availability checked</h3>
              <p className="text-[#9ca3af] text-[0.78rem] leading-relaxed">
                All members&apos; working hours were evaluated.
              </p>
            </div>
          )}
          {relaxedHardBoundaryMemberName ? (
            <div className="bg-[#f9fafb] rounded-xl p-4 hover:bg-[#f0fdfa] transition-colors duration-200">
              <div className="w-9 h-9 rounded-xl bg-[#f0fdfa] border border-[#0d9488]/10 flex items-center justify-center mb-3">
                <ShieldCheck size={17} className="text-[#0d9488]" />
              </div>
              <h3 className="text-[#1a1a2e] text-[0.84rem] font-semibold mb-1">Hard boundary temporarily relaxed</h3>
              <p className="text-[#9ca3af] text-[0.78rem] leading-relaxed">
                {relaxedHardBoundaryMemberName
                  ? `One blocked time range was relaxed for ${relaxedHardBoundaryMemberName} in this preview.`
                  : "One blocked time range was temporarily relaxed in this preview."}
              </p>
            </div>
          ) : (
            <div className="bg-[#f9fafb] rounded-xl p-4 hover:bg-[#f0fdfa] transition-colors duration-200">
              <div className="w-9 h-9 rounded-xl bg-[#f0fdfa] border border-[#0d9488]/10 flex items-center justify-center mb-3">
                <ShieldCheck size={17} className="text-[#0d9488]" />
              </div>
              <h3 className="text-[#1a1a2e] text-[0.84rem] font-semibold mb-1">Hard boundaries respected</h3>
              <p className="text-[#9ca3af] text-[0.78rem] leading-relaxed">
                No meetings were scheduled during blocked time ranges.
              </p>
            </div>
          )}
          <div className="bg-[#f9fafb] rounded-xl p-4 hover:bg-[#f0fdfa] transition-colors duration-200">
            <div className="w-9 h-9 rounded-xl bg-[#f0fdfa] border border-[#0d9488]/10 flex items-center justify-center mb-3">
              <RotateCw size={17} className="text-[#0d9488]" />
            </div>
            <h3 className="text-[#1a1a2e] text-[0.84rem] font-semibold mb-1">Rotation generated</h3>
            <p className="text-[#9ca3af] text-[0.78rem] leading-relaxed">
              The schedule distributes meeting inconvenience across the cycle.
            </p>
          </div>
        </div>
      </section>

      {!embedded && (
        <div className="pt-6">
          <PageBackLink
            href={demoMode ? undefined : `${scheduleBasePathResolved}/${scheduleId}${scheduleLinkSuffix}`}
            onClick={demoMode ? onBackToSchedule : undefined}
            className="mb-0"
          >
            Back to schedule
          </PageBackLink>
        </div>
      )}
    </main>
  )
}
