import { TeamMember, BurdenRecord, RotationWeek } from "./types"

export const mockTeam: TeamMember[] = [
  {
    id: "sarah",
    name: "Sarah Chen",
    role: "Product Lead",
    timezone: "PST (UTC-8)",
    utcOffset: -8,
    city: "San Francisco",
    workingHoursStart: "9:00 AM",
    workingHoursEnd: "6:00 PM",
    initials: "SC",
  },
  {
    id: "marcus",
    name: "Marcus Weber",
    role: "Engineering Lead",
    timezone: "CET (UTC+1)",
    utcOffset: 1,
    city: "Berlin",
    workingHoursStart: "9:00 AM",
    workingHoursEnd: "6:00 PM",
    initials: "MW",
  },
  {
    id: "priya",
    name: "Priya Sharma",
    role: "Senior Engineer",
    timezone: "IST (UTC+5:30)",
    utcOffset: 5.5,
    city: "Bangalore",
    workingHoursStart: "9:30 AM",
    workingHoursEnd: "6:30 PM",
    initials: "PS",
  },
  {
    id: "tomoko",
    name: "Tomoko Hayashi",
    role: "Design Lead",
    timezone: "JST (UTC+9)",
    utcOffset: 9,
    city: "Tokyo",
    workingHoursStart: "10:00 AM",
    workingHoursEnd: "7:00 PM",
    initials: "TH",
  },
  {
    id: "david",
    name: "David Park",
    role: "Backend Lead",
    timezone: "AEST (UTC+10)",
    utcOffset: 10,
    city: "Sydney",
    workingHoursStart: "9:00 AM",
    workingHoursEnd: "6:00 PM",
    initials: "DP",
  },
  {
    id: "alex",
    name: "Alex Rivera",
    role: "Frontend Lead",
    timezone: "BRT (UTC-3)",
    utcOffset: -3,
    city: "São Paulo",
    workingHoursStart: "9:00 AM",
    workingHoursEnd: "6:00 PM",
    initials: "AR",
  },
]

export const mockBurden: BurdenRecord[] = [
  { memberId: "priya", comfortable: 4, stretch: 4, sacrifice: 4, total: 12, burdenPercent: 50 },
  { memberId: "tomoko", comfortable: 5, stretch: 3, sacrifice: 4, total: 12, burdenPercent: 46 },
  { memberId: "david", comfortable: 6, stretch: 4, sacrifice: 2, total: 12, burdenPercent: 33 },
  { memberId: "marcus", comfortable: 7, stretch: 3, sacrifice: 2, total: 12, burdenPercent: 29 },
  { memberId: "alex", comfortable: 7, stretch: 4, sacrifice: 1, total: 12, burdenPercent: 25 },
  { memberId: "sarah", comfortable: 8, stretch: 3, sacrifice: 1, total: 12, burdenPercent: 21 },
]

export const mockRotation: RotationWeek[] = [
  { week: 1, dateRange: "Mar 9 – 13", memberId: "sarah", localTime: "10:00 PM", type: "stretch" },
  { week: 2, dateRange: "Mar 16 – 20", memberId: "alex", localTime: "11:00 PM", type: "stretch" },
  { week: 3, dateRange: "Mar 23 – 27", memberId: "marcus", localTime: "6:30 AM", type: "stretch" },
  { week: 4, dateRange: "Mar 30 – Apr 3", memberId: "david", localTime: "6:00 AM", type: "stretch" },
  { week: 5, dateRange: "Apr 6 – 10", memberId: "sarah", localTime: "10:00 PM", type: "stretch" },
  { week: 6, dateRange: "Apr 13 – 17", memberId: "alex", localTime: "11:00 PM", type: "stretch" },
  { week: 7, dateRange: "Apr 20 – 24", memberId: "marcus", localTime: "6:30 AM", type: "stretch" },
  { week: 8, dateRange: "Apr 27 – May 1", memberId: "david", localTime: "6:00 AM", type: "stretch" },
]
